version: "3.8"

services:
  webone:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data/webone.conf.d:/etc/webone.conf.d
      - ./data/webone.log:/var/log/webone.log
    restart: unless-stopped
